name: example
description: This is a turi project
version: 1.0.0
author: WessMasterFlash
license: BSD
system:
  language: python == 3.6
env:
  data_path: data/
  artifacts_path: artifacts/
  data_src: cats_dogs
  model_name: ImageClassifier
  output: coreml
  training_split: 0.8
  epochs: 10
  batch_size: 64
  gpu: 0
tasks:
  mjp: 'echo "this is for Michael"'
commands:
  data:
    load: python src/data_load.py
    clean: python src/data_clean.py
  train: python src/train.py
  export: python src/export.py
  deploy: python src/deploy.py
