#
#  activate
#  Parago
# 
#  Created by Wess Cope (wess@skafos.ai) on 07/11/19
#  Copyright 2019 Skafos,llc.
#
#   Generated by Parago
#

deactivate() {
  if ! [ -z "${_SYSTEM_PATH+_}" ] ; then
    PATH="$_SYSTEM_PATH"
    export PATH

    unset _SYSTEM_PATH
  fi

  if [ -n "${BASH-}" ] || [ -n "${ZSH_VERSION-}" ] ; then
    hash -r 2>/dev/null
  fi

  if ! [ -z "${_OLD_PS1+_}" ] ; then
    PS1="$_OLD_PS1"
    export PS1
    
    unset _OLD_PS1
  fi

  unset VIRTUAL_ENV
  if [ ! "${1-}" = "nondestructive" ] ; then
    unset -f deactivate
  fi
}

deactivate nondestructive

VIRTUAL_ENV='#{ENV_DIR}'
export VIRTUAL_ENV

_SYSTEM_PATH="$PATH"

PATH="#{EXEC_PATH}:$PATH"
export PATH

if [ -z "${VIRTUAL_DISABLE_PROMPT-}" ] ; then
  _OLD_PS1="${PS1-}"
  if [ "x" != x ] ; then
    PS1="${PS1-}"
  else
    PS1="(`basename \"$VIRTUAL_ENV\"`) ${PS1-}"
  fi

  export PS1
fi

if [ -n "${BASH}" ] || [ -n "${ZSH_VERSION-}" ] ; then
  hash -r 2>/dev/null
fi
